### ISSUE TITLE
Show snack bar when network request fails

### ISSUE THREAD

**Issue by singaltanmay** [singaltanmay/flutter-notes#6]
Tried to sign in but did not get any response. Bottom sheet modal also did not open. Error in Flutter run dialog -

```

Error: XMLHttpRequest error.
    dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/http/src/browser_client.dart 69:22                                       <fn>
dart-sdk/lib/async/zone.dart 1687:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 160:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 767:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 796:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 593:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1288:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37254:58                              <fn>


    at Object.createErrorWithStack (http://localhost:55627/dart_sdk.js:5076:12)
    at Object._rethrow (http://localhost:55627/dart_sdk.js:40477:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55627/dart_sdk.js:40473:13)
    at Object._microtaskLoop (http://localhost:55627/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:55627/dart_sdk.js:40336:13)
    at http://localhost:55627/dart_sdk.js:35811:9
```

**Comment by abhishek-jain-1999** [comment]
ismain cases bana aur response ki body main reason bhej de

eg sign in ke case main 2 hoge password wrong or user does not exist so backend se yha par bheje ga
